django-homework_1.03.2023/app_django/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app_name_task_list'  # todo
urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.home, name=''),
    path('home/', views.home, name='home'),
    path('sign_in/', views.sing_in, name='sign_in'),
    path('logout/', views.logout_, name='logout'),
    path('sign_up/', views.sign_up, name='register'),
    path('post/', views.post, name="post"),

    path('post/<int:pk>/', views.post_detail, name="post_detail"),  # под капотом - регулярное выражение
    path('post_comment_create/<int:pk>/', views.post_comment_create, name='post_comment_create'),

    path('task/create/', views.create, name='create'),
    path('task/<int:task_id>/', views.read, name='read'),
    path('task/list/', views.read_list, name='read_list'),
    path('task/<int:task_id>/update/', views.update, name='update'),
    re_path(r'^task/(?P<task_id>[0-9]+)/delete/$', views.delete, name='delete'),
    path('post_ph/<int:post_id>/', views.post_ph, name='post_ph'),
    # path('post/comment', views.post_comment, name='post_comment')

    # TODO ################################
    re_path(r'^todo/list1/$', views.todo_list1, name='todo_list1'),
    path('todo/list2/', views.TodoList2.as_view(), name='todo_list2'),
    path('user-form/', views.user_form, name='user_form'),
    # TODO ################################
]

django-homework_1.03.2023/templates/pages/Post_detail.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}
{% load app_django_extras %}
{% today True as develop %}

{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Home page' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}Register{% endblock header %}

{% block description %}this page contains global information about project{% endblock description %}

{% block main %}

<ul>
{% for i in names %}
    <li><a href="{% url "app_name_task_list:post_detail" i.id  %}">{{ i.pretty }}</a><li>
{% endfor %}
</ul>

{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/templates/pages/home.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Home page' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}Home page{% endblock header %}

{% block description %}this page contains global information about project{% endblock description %}

{% block main %}
<div class="px-4 pt-5 text-center border-bottom">
    <h1 class="display-4 fw-bold">'task list' project</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead">
            Custom created Django 'Native' web-app. Native - is UI(User Interface) based develop only on Django-templates(MVT) without any frontend framework(react/vue/angular).
        </p>
        <p class="lead mb-4">This simple project contains:
            <ul class=" custom-background-transparent-middle">
                <li class="">django: based on MVT (Model-View-Template) pattern</li>
                <li class="">django: CRUD(Create-Read-Update-Delete)-like endpoints</li>
                <li class="">django: with 'static' data and external 'templates' folder</li>
                <li class="">django: custom templatetags, filters, context-processors</li>
                <li class="">django-template: scalable extends/include structure</li>
                <li class="">django-template: Paginator</li>
                <li class="">production: with all cmd+sh scripts (+ comments)</li>
                <li class="">bootstrap css styles + js scripts</li>
                <li class="">custom css styles (with font-family: 'Zen Kaku Gothic Antique')</li>
                <li class="">and more...</li>
            </ul>
        </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
        <a class="text-decoration-none lead btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'app_name_task_list:read_list' %}">
            START!
        </a>
    </div>
    </div>
    <div class="overflow-hidden" style="max-height: 30vh;">
        <div class="container px-5">
            <img src="{% static 'img/prstcreen.png' %}" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
        </div>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/templates/pages/login.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Home page' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}Sign In{% endblock header %}

{% block description %}this page contains global information about project{% endblock description %}

{% block main %}

    <form method="POST" action="{% url "app_name_task_list:sign_in" %}" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Login</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="usernameHelp" placeholder="Ваш логин" required name="username"/>
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ваш пароль" required name="password"/>
  </div>
  <button type="submit" class="btn btn-primary">Войти</button>
</form>

{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/templates/pages/register.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Home page' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}Register{% endblock header %}

{% block description %}this page contains global information about project{% endblock description %}

{% block main %}

    <form method="POST" action="{% url "app_name_task_list:register" %}" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="usernameHelp" placeholder="Ваш логин" required name="username"/>
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ваш пароль" required name="password"/>
  </div>
  <button type="submit" class="btn btn-primary">Создать</button>
</form>

{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/templates/pages/success.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block content %}
        <h2>Thank you for your submission!</h2>
    {% endblock %}
</body>
</html>

django-homework_1.03.2023/templates/pages/user_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>User Form</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
</body>
</html>