django-homework_1.03.2023/app_django/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app_name_task_list'  # todo
urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.home, name=''),
    path('home/', views.home, name='home'),
    path('sign_in/', views.sing_in, name='sign_in'),
    path('logout/', views.logout_, name='logout'),
    path('sign_up/', views.sign_up, name='register'),
    path('post/', views.post, name="post"),

    path('post/<int:pk>/', views.post_detail, name="post_detail"),  # под капотом - регулярное выражение
    path('post_comment_create/<int:pk>/', views.post_comment_create, name='post_comment_create'),

    path('task/create/', views.create, name='create'),
    path('task/<int:task_id>/', views.read, name='read'),
    path('task/list/', views.read_list, name='read_list'),
    path('task/<int:task_id>/update/', views.update, name='update'),
    re_path(r'^task/(?P<task_id>[0-9]+)/delete/$', views.delete, name='delete'),
    path('post_ph/<int:post_id>/', views.post_ph, name='post_ph'),
    # path('post/comment', views.post_comment, name='post_comment')

    # TODO ################################
    re_path(r'^todo/list1/$', views.todo_list1, name='todo_list1'),
    path('todo/list2/', views.TodoList2.as_view(), name='todo_list2'),
    path('user-form/', views.user_form, name='user_form'),
    # TODO ################################
]

django-homework_1.03.2023/templates/components/aborted.html
<hr/>
<div class="container">
    <div class="container-fluid">
        <p class="lead text-center text-danger">Not have any data!</p>
    </div>
</div>
<hr/>

django-homework_1.03.2023/templates/components/base.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="just for fun">
    <meta name="author" content="Bogdan">
    <meta name="generator" content="Custom">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head %}{% endblock head %}
    <title>
        {% block title %}Page Title{% endblock title %}
    </title>
    {% block prestyle %}{% endblock prestyle %}
    {% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
    {#<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font_awesome_6_0_0/css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font_zen/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    {% block poststyle %}{% endblock poststyle %}
</head>
<body class="d-flex flex-column h-100 custom_body_1" style="min-height: 100vh;">
    {% block navbar %}{% endblock navbar %}
    <main class="flex-shrink-0">
        <div class="container-fluid">
            <div class="container">
                <div class="container-fluid">
                    <div class="text-center">
                        <h1 class="display-5 fw-bold fst-italic">{% block header %}{% endblock header %}</h1>
                        <div class="col-lg-6 mx-auto">
                            <p class="lead mb-4">{% block description %}{% endblock description %}</p>
                        </div>
                    </div>
                </div>
            </div>
            <main class="container p-0 custom_main_1">
                {% block main %}{% endblock main %}
            </main>
        </div>
    </main>
    {% block footer %}{% endblock footer %}
    {% block prescript %}{% endblock prescript %}
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    {% block postscript %}{% endblock postscript %}
</body>
</html>

django-homework_1.03.2023/templates/components/error.html
<hr/>
<div class="container">
    <div class="container-fluid">
        <p class="lead text-center text-danger">Error: {{ detail }} ({{ extra }})</p>
    </div>
</div>
<hr/>

django-homework_1.03.2023/templates/components/footer.html
<footer class="container-fluid mt-auto footer page-footer custom-background-transparent-middle-hard">
    <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
        <li class="m-1 p-1">
            <div class="navbar">
                <a class="btn btn-sm btn-outline-secondary" href="#">to TOP</a>
            </div>
        </li>
        <li class="m-1 p-1">
            <div class="navbar dropup">
                <a class="dropdown-toggle btn btn-sm  btn-outline-danger" role="button" data-bs-toggle="dropdown">Help!</a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <strong class="dropdown-header">Mobile phone</strong>
                            <a class="dropdown-item disabled" href="#">+7 747 261 03 59</a>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <strong class="dropdown-header">Email (google)</strong>
                        <a class="dropdown-item disabled" href="#">bogdandrienko@gmail.com</a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</footer>

django-homework_1.03.2023/templates/components/navbar.html
{% load app_django_extras %}

<nav class="container-fluid navbar navbar-expand-lg navbar-light custom-background-transparent-middle-hard">
    <a class="navbar-brand" href="{% url 'app_name_task_list:' %}">MAIN</a>
    <a class="navbar-brand" href="{% url 'app_name_task_list:home' %}">Home</a>
    <a class="navbar-brand" target="_blank" href="/admin">Admin</a>

    {% if request.user.is_authenticated %}
        <a class="m-1 text-danger" href="{% url 'app_name_task_list:logout' %}">Logout<i class="fa-solid fa-door-open"></i></a>
        <div>[{{request.user.username}}]</div>
    {% else %}

        <a class="m-1 text-secondary" href="{% url 'app_name_task_list:sign_in' %}">Sign In<i class="fa-solid fa-right-to-bracket"></i></a>
        <a class="m-1 text-secondary" href="{% url 'app_name_task_list:register' %}">Sign Up <i class="fa-solid fa-user-plus"></i></a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% access_tag 'module_modules' as module_modules %}
    {% if module_modules %}
        <ul class="navbar-nav navbar-collapse collapse" id="navbarSupportedContent">
            {% access_tag 'superuser' as superuser %}
            {% if superuser %}
                <li class="dropend">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                        Task list
                        <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill"> {{ task_count }}</i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li>
                            <strong class="dropdown-header">Todo list</strong>
                            {% access_tag 'develop' as develop %}
                            {% if develop %}
                                <a class="dropdown-item" href="{% url 'app_name_task_list:create' %}">
                                    <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                                    task create
                                </a>
                            {% endif %}
                            {% access_tag 'develop' as develop %}
                            {% if develop %}
                                <a class="dropdown-item" href="{% url 'app_name_task_list:read_list' %}">
                                    <i class="fa-solid fa-list m-0 p-1"></i>
                                    <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill"> {{ user_count }}, usere</i>
                                    task list
                                    <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill"> {{ task_count }}</i>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</nav>

django-homework_1.03.2023/templates/components/paginator.html
<div class="pagination m-3 bd-example">
    <ul class="pagination">

        {% if page.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% if page.number != 1 %}
            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
        {% endif %}

        {% if page.paginator.num_pages > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>
        {% endif %}

        {% if page.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}

    </ul>
</div>