django-homework_20.02.2023/django_facebook/django_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app_name_django_app'  # namespace
urlpatterns = [
    # path('index/', views.index),
    # path('json_api/', views.json_index),
    # path('class/', views.GetUsers.as_view()),

    path('index/', views.index, name='index'),
    path('', views.home, name=''),
    path('home/', views.home, name='home'),

    path('post/create/', views.create, name='create'),
    path('post/<int:post_id>/', views.read, name='read'),
    path('post/list/', views.read_list, name='read_list'),
    path('post/<int:post_id>/update/', views.update, name='update'),
    re_path(r'^post/(?P<post_id>\d+)/delete/$', views.delete, name='delete'),  # 'task/<int:post_id>/delete/'
]

django-homework_20.02.2023/django_facebook/django_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django_app import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    # path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', views.home, name=''),

    path('', include("django_app.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-homework_20.02.2023/django_facebook/django_app/models.py
# from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class PostModel(models.Model):
    author = models.ForeignKey(User, default="", on_delete=models.CASCADE)
    title = models.CharField(
        verbose_name="Заголовок",
        default="",
        editable=True,
        blank=True,
        db_index=True,
        max_length=150
    )
    description = models.TextField(
        verbose_name="Описание",
        default="",
        editable=True,
        blank=True
    )
    is_moderate = models.BooleanField(default=False)
    updated = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        app_label = 'django_app'
        ordering = ('id',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return f"Post: {self.title} {self.description[:30]} [{self.pk}]"

django-homework_20.02.2023/django_facebook/django_app/forms.py
from django import forms
from django.contrib import admin
# from ckeditor.widgets import CKEditorWidget
from django_app import models


# class PostAdminForm(forms.ModelForm):
#     title = forms.CharField(widget=forms.TextInput(attrs={'class': 'text-danger form-control'}))
#     content = forms.CharField(widget=CKEditorWidget(config_name="awesome_ckeditor"))
#
#     class Meta:
#         model = models.PostModel
#         fields = '__all__'


# class PostAdmin(admin.ModelAdmin):
#     form = PostAdminForm
#
#
# admin.site.register(models.PostModel, PostAdmin)

django-homework_20.02.2023/django_facebook/django_app/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest, JsonResponse

from django.urls import reverse
from django.views import View
from django.contrib.auth.models import User
from django_app import models

"""
Приложение для публикации постов (Post - сущность) - CRUD (CREATE - auth(login/logout), superuser/moder/user, , )




"""


def paginate(request, objects):
    paginator = Paginator(objects, 10)
    pages = request.GET.get('page')
    try:
        local_page = paginator.page(pages)
    except PageNotAnInteger:
        local_page = paginator.page(1)
    except EmptyPage:
        local_page = paginator.page(paginator.num_pages)
    return local_page


def index(request: HttpRequest) -> HttpResponse:
    return HttpResponse("Django app running...")


def json_index(request: HttpRequest) -> JsonResponse:
    return JsonResponse({"data": "anydata"}, safe=False, status=201)


def home(request: HttpRequest) -> HttpResponse:
    post1 = models.PostModel.objects.get()
    # form1 = forms.PostAdminForm()
    return render(request, 'django_app/home.html', {"post": post1})


def read(request: HttpRequest, post_id) -> HttpResponse:
    user = request.user
    author = models.PostModel.objects.get(id=post_id).author

    context = {"page": None, "is_my_post": user == author}
    return render(request, 'django_app/post_list.html', context=context)


class Product:
    def check_is_have(self):
        pass

    def add_if_unique(self):
        pass


def read_list(request: HttpRequest) -> HttpResponse:
    post_list = models.PostModel.objects.filter(is_moderate=True)
    page = paginate(request=request, objects=post_list)
    user = request.user
    list_owners = []
    for i in post_list:
        i.description = i.description[:10]
        list_owners.append({"post_id": i.id, "is_my_post": user.username == i.author.username})
    context = {"page": page, "list_owners": list_owners}

    return render(request, 'django_app/post_list.html', context=context)


def create(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        context = {}
        return render(request, 'django_app/post_create.html', context=context)
    elif request.method == "POST":
        print("request: ", request)
        # print("request.data: ", request.data)
        print("request.POST: ", request.POST)
        print("request.GET: ", request.GET)
        print("request.META: ", request.META)

        title = request.POST.get('title', None)
        description = request.POST.get('description', "")
        post = models.PostModel.objects.create(
            title=title,
            description=description,
        )
        return redirect(reverse('django_app:post_list', args=()))


def update(request: HttpRequest, post_id) -> HttpResponse:
    if request.method == 'POST':
        post = models.PostModel.objects.get(id=post_id)
        if post.is_moderate:
            post.is_moderate = False
        post.save()

    return redirect(reverse('app_name_django_app:read_list', args=()))


def delete(request: HttpRequest, post_id) -> HttpResponse:
    print("pass")
    return redirect(reverse('app_name_django_app:read_list', args=()))


class GetUsers(View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        # await asyncio.sleep(1)
        print(User.objects.filter(is_active=True))
        return HttpResponse("Hello World!")

django-homework_20.02.2023/django_facebook/templates/components/base.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="just for fun">
    <meta name="author" content="Bogdan">
    <meta name="generator" content="Custom">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block head %}{% endblock head %}
    <title>
        {% block title %}Page Title{% endblock title %}
    </title>
    {% block prestyle %}{% endblock prestyle %}
    {% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
    {#<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/bootstrap/bootstrap.min.bootstrap">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-5.2.3/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-6.3.0/css/bootstrap/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font_zen/style.bootstrap' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}">
    {% block poststyle %}{% endblock poststyle %}
</head>
<body class="d-flex flex-column h-100 custom_body_1" style="min-height: 100vh;">
    {% block navbar %}{% endblock navbar %}
    <main class="flex-shrink-0">
        <div class="container-fluid">
            <div class="container">
                <div class="container-fluid">
                    <div class="text-center">
                        <h1 class="display-5 fw-bold fst-italic">{% block header %}{% endblock header %}</h1>
                        <div class="col-lg-6 mx-auto">
                            <p class="lead mb-4">{% block description %}{% endblock description %}</p>
                        </div>
                    </div>
                </div>
            </div>
            <main class="container p-0 custom_main_1">
                {% block main %}{% endblock main %}
            </main>
        </div>
    </main>
    {% block footer %}{% endblock footer %}
    {% block prescript %}{% endblock prescript %}
    <script src="{% static 'js/bootstrap-5.2.3/bootstrap.min.js' %}"></script>
    {% block postscript %}{% endblock postscript %}
</body>
</html>

django-homework_20.02.2023/django_facebook/templates/components/navbar.html
{% load app_django_extras %}

<nav class="container-fluid navbar navbar-expand-lg navbar-light custom-background-transparent-middle-hard">
    <a class="navbar-brand" href="{% url 'app_name_django_app:' %}">MAIN</a>
    <a class="navbar-brand" href="{% url 'app_name_django_app:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% access_tag 'module_modules' as module_modules %}
    {% if module_modules %}
        <ul class="navbar-nav navbar-collapse collapse" id="navbarSupportedContent">
            {% access_tag 'superuser' as superuser %}
            {% if superuser %}
                <li class="dropend">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                        Task list
                        <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill"> {{ task_count }}</i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li>
                            <strong class="dropdown-header">Todo list</strong>
                            {% access_tag 'develop' as develop %}
                            {% if develop %}
                                <a class="dropdown-item" href="{% url '' %}">
                                    <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                                    task create
                                </a>
                            {% endif %}
                            {% access_tag 'develop' as develop %}
                            {% if develop %}
                                <a class="dropdown-item" href="{% url '' %}">
                                    <i class="fa-solid fa-list m-0 p-1"></i>
                                    task list
                                    <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill"> {{ task_count }}</i>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</nav>

django-homework_20.02.2023/django_facebook/templates/components/paginator.html
<div class="pagination m-3 bd-example">
    <ul class="pagination">

        {% if page.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% if page.number != 1 %}
            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
        {% endif %}

        {% for num in "23456789" %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endfor %}

        {% if page.paginator.num_pages > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>
        {% endif %}

        {% if page.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}

    </ul>
</div>

django-homework_20.02.2023/django_facebook/templates/django_app/home.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Home page' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
{#    {% include 'components/navbar.html' %}#}
{% endblock navbar %}

{% block header %}Home page{% endblock header %}

{% block description %}this page contains global information about project{% endblock description %}

{% block main %}
<div class="px-4 pt-5 text-center border-bottom">
    <h1 class="display-4 fw-bold">'task list' project</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead">
            Custom created Django 'Native' web-app. Native - is UI(User Interface) based develop only on Django-templates(MVT) without any frontend framework(react/vue/angular).
        </p>
        <p class="lead mb-4">This simple project contains:
            <ul class=" custom-background-transparent-middle">
                <li class="">django: based on MVT (Model-View-Template) pattern</li>
                <li class="">django: CRUD(Create-Read-Update-Delete)-like endpoints</li>
                <li class="">django: with 'static' data and external 'templates' folder</li>
                <li class="">django: custom templatetags, filters, context-processors</li>
                <li class="">django-template: scalable extends/include structure</li>
                <li class="">django-template: Paginator</li>
                <li class="">production: with all cmd+sh scripts (+ comments)</li>
                <li class="">bootstrap css styles + js scripts</li>
                <li class="">custom css styles (with font-family: 'Zen Kaku Gothic Antique')</li>
                <li class="">and more...</li>
            </ul>
        </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
        <a class="text-decoration-none lead btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'app_name_django_app:create' %}">
            START!
        </a>
    </div>
    </div>
    <div class="overflow-hidden" style="max-height: 30vh;">
        <div class="container px-5">
            <img src="{% static 'img/prstcreen.png' %}" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
        </div>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_20.02.2023/django_facebook/templates/django_app/post_create.html
{% block main %}
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    {% block prestyles %}{% endblock prestyles %}
    <link href="signin.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/fontawesome/css/all.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/css/my.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
{#      <li style="margin-right: 15px;">#}
{#                                  <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; z-index: 1; border-radius: 100%;">#}
{#          {% if user.is_authenticated %}#}
{#            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2">Profile({{ user.username}})</a>#}
{#        {% else %}#}
{#            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2">Profile(anonymous)</a>#}
{#        {% endif %}#}
{#          </li>#}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
        </li>
        <a href="{% url 'app_name_django_app:home' %}" class="btn btn-outline-primary" type="submit" style="margin-right: 8px;">Home</a>
        <a href="{% url 'app_name_django_app:read_list' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">All posts</a>
      </ul>
{#      <form class="d-flex">#}
{#        <div class="text-end">#}
{#          {% if user.is_authenticated %}#}
{#              <a href="{% url 'app_name_django_app:login' %}" type="button" class="btn btn-outline-danger me-2">Logout</a>#}
{#          {% else %}#}
{#              <a href="{% url 'app_name_django_app:logout' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>#}
{#          {% endif %}#}
{#          </div>#}
{#      </form>#}
    </div>
  </div>
</nav>
    <div class="container container-fluid">
        <i class="fa-solid fa-user"></i>
        <i class="fa-solid fa-comment"></i>
        <main class="form-signin">
            <form action="{% url 'app_name_django_app:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal">Add your new post!</h1>
                Title:
                <input type="text" class="form-control m-3" placeholder="Enter here your title" name="title">
                Description:
                <textarea type="text" class="form-control m-3" rows="5" name="description" placeholder="Enter here your discription"></textarea>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Post</button>
            </form>
        </main>
    </div>

{% endblock main %}

django-homework_20.02.2023/django_facebook/templates/django_app/post_list.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}

    Post List

{% block main %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
{#          <li style="margin-right: 15px;">#}
{#                        <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; z-index: 1; border-radius: 100%;">#}
{#          {% if user.is_authenticated %}#}
{#            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2">Profile({{ user.username}})</a>#}
{#        {% else %}#}
{#            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2">Profile(anonymous)</a>#}
{#        {% endif %}#}
{#          </li>#}
        <li class="nav-item">
        <a href="{% url 'app_name_django_app:home' %}" class="btn btn-outline-primary" type="submit">Home</a>
        <a href="{% url 'app_name_django_app:create' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">Create new post</a>
      </ul>
{#      <form class="d-flex">#}
{#        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#        <div class="text-end">#}
{#          {% if user.is_authenticated %}#}
{#              <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2">Logout</a>#}
{#          {% else %}#}
{#              <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>#}
{#          {% endif %}#}
{#          </div>#}
{#      </form>#}
    </div>
  </div>
</nav>
<h1 align="center">All posts</h1>
    <div class="container container-fluid">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for post in posts %}
            <div class="col">
              <div class="card shadow-sm" style="border-radius: 30px;">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false" style="border-radius: 30px;"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ post.title }}</text></svg>
                <div class="card-header" align="center">{{ post.title }}</div>
                <div class="card-body">
                  <p class="card-text">{{ post.description }}</p>
                  <div class="d-flex justify-content-between align-items-center" >
                    <div class="btn-group">
{#                      <a href="{% url '' post.id %}" type="button" class="btn btn-sm btn-outline-secondary">Details...</a>#}
                      <a href="#" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                    <small class="text-muted">
                        <a href="{% url 'app_name_django_app:delete' post.id %}" class="text-decoration-none btn"><i class="fa-solid fa-trash-can text-danger">Delete</i></a>
                    </small>
                    <div style="margin-left: 300px; border: 1px solid #E1C16E; text-align: center;">
                    {{ forloop.counter }}
                  </div>
                </div>
              </div>

            </div>

        {% endfor %}
      </div>
    </div>
    <div class="container d-flex justify-content-center align-self-center">
        {% include 'components/paginator.html' %}
    </div>
{% endblock main %}

django-homework_20.02.2023/django_facebook/templates/django_twitter_app/create_users.html
{% extends "components/base.html" %}
{% load static %}

{% block title %}Create users{% endblock title %}
{% block main %}

<section class="py-5 text-center container">
    <main class="form-signin">
  <form action="{% url 'django_twitter_app:create_users' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Введите свои данные</h1>

    <div class="form-floating">
      <input type="file" accept=".xls, .xlsx, .xlsx" class="form-control" id="floatingInput" placeholder="name@example.com" required name="excel">
      <label for="floatingInput">Вставьте файл</label>
    </div>
      <div class="input-group">
          <a href="{% static "media/admin/export_users.xlsx" %}" class="w-50 btn btn-lg btn-danger" type="submit">скачать шаблон</a>
          <button class="w-50 btn btn-lg btn-primary" type="submit">Загрузить</button>
      </div>

  </form>
</main>
</section>


{% endblock main %}

django-homework_20.02.2023/django_facebook/templates/django_twitter_app/home.html
{% extends "components/base.html" %}

{% block title %}Twitter Home{% endblock title %}
{% block main %}

<section class="py-5 text-center container">
    <div class="px-4 py-5 my-5 text-center">
    <img class="d-block mx-auto mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="display-5 fw-bold">Centered hero</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="{% url 'django_twitter_app:post_list' %}" type="button" class="btn btn-primary btn-lg px-4 gap-3">Все посты</a>
        <a href="{% url 'django_twitter_app:post_create' %}" type="button" class="btn btn-outline-secondary btn-lg px-4">Опубликовать свой пост</a>
      </div>
    </div>
  </div>
</section>


{% endblock main %}

django-homework_20.02.2023/django_facebook/templates/django_twitter_app/login.html
{% extends "components/base.html" %}

{% block title %}Login{% endblock title %}
{% block main %}

<section class="py-5 text-center container">
    <main class="form-signin">
  <form action="{% url 'django_twitter_app:login' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Введите свои данные</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="username">
      <label for="floatingInput">Имя пользователя</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
      <label for="floatingPassword">Пароль</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
  </form>
</main>
</section>


{% endblock main %}

django-homework_20.02.2023/django_facebook/templates/django_twitter_app/post_create.html
{% extends "components/base.html" %}

{% block title %}Добавление{% endblock title %}
{% block main %}

    <div class="container container-fluid">
<i class="fa-solid fa-user"></i>
        <i class="fa-solid fa-comment"></i>
        <main class="form-signin">
  <form action="{% url 'django_twitter_app:post_create' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Добавьте свою публикацию!</h1>

        Заголовок:
      <input type="text" class="form-control m-3" placeholder="введите сюда заголовок..." name="title">
      Описание:
      <textarea type="text" class="form-control m-3" rows="5" name="description"></textarea>
    <button class="w-100 btn btn-lg btn-primary" type="submit">опубликовать</button>
  </form>
</main>


    </div>


{% endblock main %}

django-homework_20.02.2023/django_facebook/templates/django_twitter_app/post_update.html
{% extends "components/base.html" %}

{% block title %}Изменение{% endblock title %}
{% block main %}

    <div class="container container-fluid">
<i class="fa-solid fa-user"></i>
        <i class="fa-solid fa-comment"></i>
        <main class="form-signin">
  <form action="{% url 'django_twitter_app:post_update' post.id %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Измените свою публикацию!</h1>

        Заголовок:
      <input type="text" class="form-control m-3" placeholder="введите сюда заголовок..." name="title"
      value="{{ post.title }}"
      >
      Описание:
      <textarea type="text" class="form-control m-3" rows="5" name="description">{{ post.description }}</textarea>
    <button class="w-100 btn btn-lg btn-primary" type="submit">изменить</button>
  </form>
</main>


    </div>


{% endblock main %}