django-homework_1.03.2023/app_django/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app_name_task_list'  # todo
urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.home, name=''),
    path('home/', views.home, name='home'),
    path('sign_in/', views.sing_in, name='sign_in'),
    path('logout/', views.logout_, name='logout'),
    path('sign_up/', views.sign_up, name='register'),
    path('post/', views.post, name="post"),

    path('post/<int:pk>/', views.post_detail, name="post_detail"),  # под капотом - регулярное выражение
    path('post_comment_create/<int:pk>/', views.post_comment_create, name='post_comment_create'),

    path('task/create/', views.create, name='create'),
    path('task/<int:task_id>/', views.read, name='read'),
    path('task/list/', views.read_list, name='read_list'),
    path('task/<int:task_id>/update/', views.update, name='update'),
    re_path(r'^task/(?P<task_id>[0-9]+)/delete/$', views.delete, name='delete'),
    path('post_ph/<int:post_id>/', views.post_ph, name='post_ph'),
    # path('post/comment', views.post_comment, name='post_comment')

    # TODO ################################
    re_path(r'^todo/list1/$', views.todo_list1, name='todo_list1'),
    path('todo/list2/', views.TodoList2.as_view(), name='todo_list2'),
    path('user-form/', views.user_form, name='user_form'),
    # TODO ################################
]

django-homework_1.03.2023/app_django/templates/app_task_list/pages/post_detail.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}
{% load app_django_extras %}
{% today True as develop %}

{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Home page' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}Register{% endblock header %}

{% block description %}this page contains global information about project{% endblock description %}

{% block main %}

<div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{post.title}}</text></svg>
            <div class="card-body">
              <p class="card-text">{{post.description}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>

                </div>
                <small class="text-muted">9 mins </small>

                <small class="text-muted">status:

                    {% if post_like %}
                        <i class="fa-solid btn btn-sm btn-success fa-heart"></i>
                    {% else %}
                        <i class="fa-solid btn btn-sm btn-outline-success fa-heart"></i>
                    {% endif %}

                    {% is_my_like post.id as val1 %}
                    {% if val1 %}
                        <i class="fa-solid btn btn-sm btn-success fa-heart"></i>
                    {% else %}
                        <i class="fa-solid btn btn-sm btn-outline-success fa-heart"></i>
                    {% endif %}

                </small>
              </div>
            </div>
          </div>


<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>

<form action="{% url 'app_name_task_list:post_comment_create' post.id %}"
                  method="POST"
                  target="_self"
                  enctype="multipart/form-data"
                  name="idea_create"
                  autocomplete="on"
                  class="text-center"
        >
            {% csrf_token %}
                        <input type="hidden"
                               name="ids"
                               value="{{ post.id }}"
                                required
                               class="form-control form-control-sm"
                        />

                                <label class="form-control-sm w-50 m-1">
                        Введите свой комментарий:
                        <input type="text"
                               name="description"
                               required=""
                               value=""
                               minlength="1"
                               maxlength="300"
                               class="form-control form-control-sm"
                        />
                        <small class="text-muted">кол-во символов: <= 500</small>
                    </label>
            <li class="m-1">
                <button class="btn btn-sm btn-outline-primary" type="submit">submit</button>
            </li>
            </form>



<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 380px;">
    <a href="/" class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
      <svg class="bi pe-none me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-5 fw-semibold">List group</span>
    </a>
    <div class="list-group list-group-flush border-bottom scrollarea">
        {% for i in post.get_this_post_comments %}
      <a href="#" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <strong class="mb-1">{{ i.author}}</strong>
          <small class="text-muted">{{i.date}}</small>
        </div>
        <div class="col-10 mb-1 small">{{i.description}}</div>
      </a>

        {% endfor %}
    </div>
  </div>

{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/app_django/templates/app_task_list/pages/task_change.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='task change' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}task change{% endblock header %}

{% block description %}this page contains form with task data fields for send data to change task{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom">
        <div class="d-flex text-start">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'app_name_task_list:read_list' %}">
                <= all tasks <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ task_count }}</i>
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1 custom-background-transparent-middle m-0 p-0">
        <form action="{% url 'app_name_task_list:update' task.id %}"
                  method="POST"
                  target="_self"
                  enctype="multipart/form-data"
                  name="idea_create"
                  autocomplete="on"
                  class="text-center"
        >
            {% csrf_token %}
            <div>
                <div>
                    <label class="form-control-sm w-50 m-1">
                        Title:
                        <input type="text"
                               name="title"
                               required=""
                               placeholder="input 'title' here..."
                               value="{{ task.title }}"
                               minlength="1"
                               maxlength="300"
                               class="form-control form-control-sm"
                        />
                        <small class="text-muted">chars count: <= 300</small>
                    </label>
                    <label class="form-control-sm w-75 m-1">
                        Description:
                        <textarea type="text"
                                  name="description"
                                  required=""
                                  placeholder="input 'description' here..."
                                  minlength="1"
                                  maxlength="3000"
                                  rows="3"
                                  class="form-control form-control-sm"
                        >{{ task.description }}</textarea>
                        <small class="text-muted">chars count: <= 3000</small>
                    </label>
                </div>
            </div>
            <hr/>
            <div class="container-fluid text-center">
                <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
                    <li class="m-1">
                        <button class="btn btn-sm btn-outline-primary" type="submit">submit</button>
                    </li>
                    <li class="m-1">
                        <button class="btn btn-sm btn-outline-warning" type="reset">reset</button>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/app_django/templates/app_task_list/pages/task_create.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='task create' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}task create{% endblock header %}

{% block description %}this page contains form with fields for send data to create new task{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom">
        <div class="d-flex text-start">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'app_name_task_list:read_list' %}">
                <= all tasks <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ task_count }}</i>
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1 custom-background-transparent-middle m-0 p-0">
        <form action="{% url 'app_name_task_list:create' %}"
                  method="POST"
                  target="_self"
                  enctype="multipart/form-data"
                  name="idea_create"
                  autocomplete="on"
                  class="text-center"
        >
            {% csrf_token %}
            <div>
                <div>
                    <label class="form-control-sm w-50 m-1">
                        Title:
                        <input type="text"
                               name="title"
                               required=""
                               placeholder="input 'title' here..."
                               value=""
                               minlength="1"
                               maxlength="300"
                               class="form-control form-control-sm"
                        />
                        <small class="text-muted">chars count: <= 300</small>
                    </label>
                    <label class="form-control-sm w-75 m-1">
                        Description:
                        <textarea type="text"
                                  name="description"
                                  required=""
                                  placeholder="input 'description' here..."
                                  minlength="1"
                                  maxlength="3000"
                                  rows="3"
                                  class="form-control form-control-sm"
                        ></textarea>
                        <small class="text-muted">chars count: <= 3000</small>
                    </label>
                </div>
            </div>
            <hr/>
            <div class="container-fluid text-center">
                <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
                    <li class="m-1">
                        <button class="btn btn-sm btn-outline-primary" type="submit">submit</button>
                    </li>
                    <li class="m-1">
                        <button class="btn btn-sm btn-outline-warning" type="reset">reset</button>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/app_django/templates/app_task_list/pages/task_detail.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='task details' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}task details{% endblock header %}

{% block description %}this page contains detail data from selected task{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom m-0 p-0">
        <div class="d-flex justify-content-around">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'app_name_task_list:read_list' %}">
                <= all tasks <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ task_count }}</i>
            </a>
            <a class="text-decoration-none btn btn-sm btn-outline-success m-1 p-2" href="{% url 'app_name_task_list:create' %}">
                <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                create new task
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1">
        <div class="col">
            <div class="card custom-background-transparent-middle">
                <div class="card-header">
                    <div class="m-0 p-3">
                        <div class="d-flex justify-content-around">
                            <h5>{{task.title}}</h5>
                            <form action="{% url 'app_name_task_list:update' task.id %}"
                                  method="POST"
                                  target="_self"
                                  enctype="multipart/form-data"
                                  name="idea_create"
                                  autocomplete="on"
                                  class="m-0 p-0"
                            >
                                {% csrf_token %}
                                <div>
                                    <input type="hidden"
                                       name="is_completed"
                                       required=""
                                       placeholder=""
                                       {% if task.is_completed %}
                                            value="False"
                                       {% else %}
                                            value="True"
                                       {% endif %}
                                       minlength="1"
                                       maxlength="32"
                                       class="form-control form-control-lg"
                                />
                                </div>
                                <div class="btn-group m-0 p-1">
                                    {% if task.is_completed %}
                                        <button class="btn btn-sm btn-outline-danger m-0 p-1" type="submit">
                                            <i class="fa-solid fa-circle-xmark text-danger m-0 p-1"></i>
                                            not complete
                                        </button>
                                    {% else %}
                                        <button class="btn btn-sm btn-outline-success m-0 p-1" type="submit">
                                            <i class="fa-solid fa-circle-check text-success m-0 p-1"></i>
                                            complete
                                        </button>
                                    {% endif %}
                                    <a href="{% url 'app_name_task_list:update' task.id %}" class="btn btn-sm btn-outline-warning m-0 p-1">
                                        <i class="fa-solid fa-screwdriver-wrench text-warning m-0 p-1"></i>
                                        change
                                    </a>
                                    <a href="{% url 'app_name_task_list:delete' task.id %}" class="btn btn-sm btn-outline-danger m-0 p-1">
                                        <i class="fa-solid fa-circle-minus text-danger m-0 p-1"></i>
                                        delete
                                    </a>
                                </div>
                            </form>
                        </div>
                        {% if task.is_completed %}
                            <div class="feature-icon bg-success bg-gradient text-white">
                                <p class="m-0 p-1"></p>
                            </div>
                        {% else %}
                            <div class="feature-icon bg-danger bg-gradient text-white">
                                <p class="m-0 p-1"></p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    <p class="m-0 p-3">{{ task.description }}</p>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between m-0 p-1">
                        <small class="text-warning">
                            {{ task.created }} [created]
                        </small>
                        <small class="text-success">
                            {{ task.updated }} [updated]
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

django-homework_1.03.2023/app_django/templates/app_task_list/pages/task_list.html
{% extends "components/base.html" %}
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='task list' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block header %}task list{% endblock header %}

{% block description %}this page contains all tasks{% endblock description %}

{% block main %}
<div class="container shadow-lg custom-background-transparent-hard m-0 p-0">
    <div class="shadow border-bottom m-0 p-0">
        <div class="d-flex justify-content-around">
            <h6 class="lead fw-bold m-1 p-2">tasks <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ task_count }}</i>:</h6>
            <a class="text-decoration-none btn btn-sm btn-outline-success m-1 p-2" href="{% url 'app_name_task_list:create' %}">
                <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                create new task
            </a>
        </div>
    </div>
    <div class="text-end">
        <form action="{% url 'app_name_task_list:read_list' %}"
        method="GET"
        target="_self"
        enctype="multipart/form-data"
        name="idea_create"
        autocomplete="on"
        class="m-0 p-0"
        >
        {% csrf_token %}
        <div>
        <input type="hidden"
           name="is_detail_view"
           required=""
           placeholder=""
           {% if is_detail_view %}
                value="False"
           {% else %}
                value="True"
           {% endif %}
           minlength="1"
           maxlength="32"
           class="form-control form-control-sm"
        />
        </div>
        {% if is_detail_view %}
            <button class="btn btn-lg m-0 p-1" type="submit">
                <i class="fa-solid fa-list-check text-secondary m-0 p-1"></i>
                list view
            </button>
        {% else %}
            <button class="btn btn-lg m-0 p-1" type="submit">
                <i class="fa-solid fa-calendar-week text-secondary m-0 p-"></i>
                detail view
            </button>
        {% endif %}
        </form>
    </div>

    {% if page %}
        <div class="container d-flex justify-content-center align-self-center">
            {% include 'components/paginator.html' %}
        </div>

        {% if is_detail_view %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                {% for task in page %}
                    <div class="col">
                        <div class="card border border-1 border-dark custom-background-transparent-middle m-1 p-0">
                            <div class="card-header">
                                <div class="m-0 p-3">
                                    <div class="d-flex justify-content-around">
                                        <a class="text-decoration-none text-dark" href="{% url 'app_name_task_list:read' task.id %}">
                                            <h5>{{ task.title|cut_string:30 }} ({{task.author}})</h5>
                                        </a>
                                        <form action="{% url 'app_name_task_list:update' task.id %}"
                                              method="POST"
                                              target="_self"
                                              enctype="multipart/form-data"
                                              name="idea_create"
                                              autocomplete="on"
                                              class="m-0 p-0"
                                        >
                                            {% csrf_token %}
                                            <div>
                                                <input type="hidden"
                                                   name="is_completed"
                                                   required=""
                                                   placeholder=""
                                                   {% if task.is_completed %}
                                                        value="False"
                                                   {% else %}
                                                        value="True"
                                                   {% endif %}
                                                   minlength="1"
                                                   maxlength="32"
                                                   class="form-control form-control-sm"
                                            />
                                            </div>
                                            <div class="btn-group m-0 p-1">
                                                {% if task.is_completed %}
                                                    <button class="btn btn-sm btn-outline-danger m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-xmark text-danger m-0 p-1"></i>
                                                        not complete
                                                    </button>
                                                {% else %}
                                                    <button class="btn btn-sm btn-outline-success m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-check text-success m-0 p-1"></i>
                                                        complete
                                                    </button>
                                                {% endif %}
                                                {% if task.author == request.user %}
                                                <a href="{% url 'app_name_task_list:delete' task.id %}" class="btn btn-sm btn-outline-danger m-0 p-1">
                                                    <i class="fa-solid fa-circle-minus text-danger m-0 p-1"></i>
                                                    delete ({{task.author}} {{request.user.username}})

                                                </a>
                                                {% endif %}
                                            </div>
                                        </form>
                                    </div>
                                    {% if task.is_completed %}
                                        <div class="feature-icon bg-success bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% else %}
                                        <div class="feature-icon bg-danger bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="m-0 p-3">{{ task.description|cut_string:100 }}</p>
                            </div>
                            <div class="card-footer">
                                <div class="d-flex justify-content-between m-0 p-1">
                                    <small class="text-warning m-1 p-0">
                                        {{ task.created }} [created]
                                    </small>
                                    <small class="text-success m-1 p-0">
                                        {{ task.updated }} [updated]
                                    </small>
                                </div>
                                <a class="text-decoration-none text-dark" href="{% url 'app_name_task_list:read' task.id %}">
                                    <button class="btn btn-sm btn-outline-primary w-100 m-0 p-1" type="submit">
                                        <i class="fa-solid fa-circle-info m-0 p-1"></i>
                                        details
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="m-0 p-1">
                <ul class="m-0">
                    {% for task in page %}
                        <li class="text-start m-0 p-0 border border-1 border-dark p-1">
                            {% if task.is_completed %}
                                <div class="feature-icon bg-success d-flex justify-content-between">
                            {% else %}
                                <div class="feature-icon bg-danger d-flex justify-content-between">
                            {% endif %}
                                <a class="text-decoration-none text-white small w-50" href="{% url 'app_name_task_list:read' task.id %}">
                                    <div class="d-flex">
                                        <h6 class="lead m-1 p-1">{{ task.description|cut_string:20 }}</h6>
                                        <small class="m-0 p-2">{{ task.description|cut_string:30 }}</small>
                                    </div>
                                </a>
                                <div class="m-1 p-1">
                                    <small class="text-white m-1 p-0">
                                        {{ task.updated }} [updated]
                                    </small>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="container d-flex justify-content-center align-self-center">
            {% include 'components/paginator.html' %}
        </div>
    {% else %}
        {% include 'components/aborted.html' %}
    {% endif %}
</div>
{% endblock main %}

{% block footer %}
    {% include 'components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}